### ISSUE TITLE
I want user my own compiler with the default tag

### ISSUE THREAD

**Issue by onelongblock** [nsrosenqvist/gulp-single-file-components#1]
Hi, if I want to use my own compiler to handle the contents of the script tag, but I do not want to specify the script's lang. what should I do？
I found this writing is invalid.
```javascript
components({
    customCompilers: {
      script: function (content, cb, compiler, filePath) {
        // It does not work
        cb(null, content)
      },
      pug: function (content, cb, compiler, filePath) {
        content = pug.render(content, {doctype: 'html'})
        cb(null, content)
      }
    }
}
```

**Comment by nsrosenqvist** [comment]
I think you're confusing compilers with tags. A compiler processes the content of a tag and is specified with the `lang` attribute on the tag. If `lang` isn't set then the raw content is passed to the output file.

So with your example (assuming that you want to compile the script tag with "pug"):

```js
components({
    customCompilers: {
      pug: function (content, cb, compiler, filePath) {
        content = pug.render(content, {doctype: 'html'})
        cb(null, content)
      }
    }
}
```

```html
<script lang="pug">
   <!-- content -->
</script>
```

Tags basically only handle setting the appropriate file extension (script -> js, style -> css, etc.). At the moment there's no functionality to override the default tags (script, style and template), this might change in the future if it proves that people actually has a use case for it.

So for you, since you'd like to change how the script tag is compiled by default there's currently no straight forward way to set that up since the tag would just pass the raw output. But what you could do is to set an outputModifier:

```js
       outputModifiers: {
          script: function (lang, filePath, content, base) {
            // If the lang attribute is empty
            if (! lang) {
              return pug.render(content, {doctype: 'html'})
            }
            else {
              return content;
            }
          },
        }
```

I hope that helps!

**Comment by lbb00** [comment]
Thanks.
